docker-test/Dockerfile, docker-test/Dockerfile.python27, docker-test/main.py, docker-test/requirements.txt, hkube_python_wrapper/__version__.py, hkube_python_wrapper/hkube_api.py, hkube_python_wrapper/messages.py, hkube_python_wrapper/wc.py, test-server/server.js, test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/3)
=> Subpipeline

docker-test/main.py, hkube_python_wrapper/codeApi/execution.py, hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/wrapper/algorunner.py, tests/mock_ws_server.py, tests/test_hkube_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/9)
=> fix: handle code-api errors and storage

hkube_python_wrapper/wrapper/data_adapter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/10)
=> add more tracing

hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/storage/fs_adapter.py, hkube_python_wrapper/wrapper/data_adapter.py, setup.cfg, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/12)
=> fix not parallel zmq polling

hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/14)
=> Send "Are you there"

README.md, hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/wrapper/algorunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/13)
=> Add docs for wrapper

hkube_python_wrapper/storage/base_storage_manager.py, hkube_python_wrapper/storage/fs_adapter.py, tests/test_storage_manager_fs.py, tests/test_storage_manager_s3.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/18)
=> raise proper storage manager exceptions

hkube_python_wrapper/cache/caching.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServer.py, hkube_python_wrapper/util/encoding.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/data_adapter.py, tests/test_data_adapter.py, tests/test_encoding.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/24)
=> Multi part

hkube_python_wrapper/__init__.py, hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/codeApi/waitFor.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServer.py, hkube_python_wrapper/communication/zmq/ZMQServers.py, hkube_python_wrapper/communication/zmq/consts.py, hkube_python_wrapper/util/queueImpl.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/wc.py, setup.py, tests/conftest.py, tests/test_communication.py, tests/test_data_adapter.py, tests/test_hkube_api.py, tests/test_wrapper.py, tests/xtest_communication.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/23)
=> No more gevent

hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/communication/zmq/BaseServer.py, hkube_python_wrapper/communication/zmq/ZMQPingServer.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServer.py, hkube_python_wrapper/communication/zmq/ZMQServers.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/util/percentile.py, hkube_python_wrapper/wrapper/data_adapter.py
Separate ping to another process
ping port is default port+1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/25)
=> Ping out of proc

hkube_python_wrapper/cache/caching.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/util/encoding.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/data_adapter.py, hkube_python_wrapper/wrapper/wc.py, setup.cfg, setup.py, tests/mock_ws_server.py, tests/test_data_adapter.py, tests/test_encoding.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)
=> send header separately using multipart

hkube_python_wrapper/communication/zmq/ZMQServers.py, hkube_python_wrapper/util/timerImpl.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/wc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29)
=> Fix algorithm exit

hkube_python_wrapper/cache/caching.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/storage/base_storage_manager.py, hkube_python_wrapper/storage/fs_adapter.py, hkube_python_wrapper/storage/s3_adapter.py, hkube_python_wrapper/storage/task_output_manager.py, hkube_python_wrapper/util/encoding.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/data_adapter.py, hkube_python_wrapper/wrapper/wc.py, tests/mock_ws_server.py, tests/test_data_adapter.py, tests/test_encoding.py, tests/test_hkube_api.py, tests/test_storage_manager_fs.py, tests/test_storage_manager_s3.py, tests/xtest_encoding.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)
=> feat: add multi-part storage method

hkube_python_wrapper/communication/zmq/ZMQRequest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/30)
=> fix close, conStr typos

hkube_python_wrapper/config/config.py, tests/configs/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/31)
=> fix MAX_CACHE_SIZE

hkube_python_wrapper/communication/zmq/ZMQPingServer.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/wrapper/data_adapter.py, tests/test_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/32)
=> Remove logs

hkube_python_wrapper/storage/base_storage_manager.py, hkube_python_wrapper/storage/fs_adapter.py, hkube_python_wrapper/storage/s3_adapter.py, hkube_python_wrapper/storage/storage_manager.py, hkube_python_wrapper/util/encoding.py, tests/test_encoding.py, tests/test_storage_manager_fs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/33)
=> fix: improve decode function

hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServers.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/util/encoding.py, hkube_python_wrapper/wrapper/data_adapter.py, tests/configs/config.py, tests/test_data_adapter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/34)
=> feat: add more logs for peer request

hkube_python_wrapper/wrapper/algorunner.py, tests/test_wrapper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/37)
=> Fix module loading with path

hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, hkube_python_wrapper/storage/base_storage_manager.py, setup.py, tests/test_queue.py, tests/test_zmq.py, tests/xtest_communication.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)
=> save statistics per consumer

hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/43)
=> change needed since working with flows. Memory leak fix

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/wrapper/data_adapter.py, tests/test_hkube_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)
=> Fill missing pipeline result

hkube_python_wrapper/codeApi/hkube_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/46)
=> check storage version before attempting to access sotrage

hkube_python_wrapper/util/object_path.py, hkube_python_wrapper/wrapper/data_adapter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/47)
=> feat: improve get object path

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/wrapper/data_adapter.py, setup.cfg, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)
=> 1.3 fill missing pipeline result

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/communication/streaming/MessageProducer.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/49)
=> adding stopping report

hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/53)
=> message drift fix by waiting a heartbeat

hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/55)
=> handle a message at a time

hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/56)
=> force stop on listener

.pylintrc, hkube_python_wrapper/__init__.py, hkube_python_wrapper/cache/caching.py, hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/DataServer.py, hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/MessageProducer.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/zmq/ZMQPingServer.py, hkube_python_wrapper/communication/zmq/ZMQRequest.py, hkube_python_wrapper/communication/zmq/ZMQServer.py, hkube_python_wrapper/communication/zmq/ZMQServers.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/WorkerQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/storage/storage_manager.py, hkube_python_wrapper/util/decorators.py, hkube_python_wrapper/util/logger.py, hkube_python_wrapper/util/percentile.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/data_adapter.py, hkube_python_wrapper/wrapper/wc.py, stam.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)
=> add wrapper::LEVEL:: prefix to logs

hkube_python_wrapper/communication/streaming/MessageProducer.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, tests/test_zmq.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/58)
=> gross time

hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/wrapper/algorunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/59)
=> Print when loosing messages + not replace sockrt during close

hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/WorkerQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/60)
=> shorten poll time in producer

hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, tests/test_queue.py, tests/test_streaming.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)
=> Put messages with recipient only

hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/62)
=> feat: poll cycle

hkube_python_wrapper/communication/streaming/MessageProducer.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/63)
=> feat: streaming

hkube_python_wrapper/communication/zmq/streaming/producer/Worker.py, hkube_python_wrapper/communication/zmq/streaming/producer/WorkerQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/64)
=> fix: expired workers

hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/65)
=> sync queue access

.github/workflows/pr.yaml, hkube_python_wrapper/cache/caching.py, setup.py, tests/requirements.txt, tests/test_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/68)
=> cache-fixes

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/util/uid.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/data_adapter.py, tests/mock_ws_server.py, tests/test_hkube_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/71)
=> support storageInput for code-api

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/wrapper/data_adapter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/73)
=> fix start-algorithm for multiple input items

setup.cfg, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/74)
=> bump to 2.1

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/messages.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/75)
=> support streaming debug

hkube_python_wrapper/config/config.py, hkube_python_wrapper/util/stdout_redirector.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/messages.py, hkube_python_wrapper/wrapper/wc.py, tests/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/79)
=> optionally send logs to worker via web socket

hkube_python_wrapper/wrapper/wc.py, setup.py, tests/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)
=> Handle already connected for debug

hkube_python_wrapper/util/logger.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/80)
=> logger level

hkube_python_wrapper/config/config.py, hkube_python_wrapper/storage/s3_adapter.py, tests/configs/config.py, tests/test_storage_manager_s3.py, tools/ci/tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81)
=> allow ssl_no_verify for s3

.github/workflows/pr.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/82)
=> add 3.9 and 3.10

hkube_python_wrapper/util/url_encode_impl.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/messages.py, hkube_python_wrapper/wrapper/wc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/83)
=> improve debug already connected handling

setup.cfg, setup.py
set release to build 2.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/84)
=> release 2.4.0

.github/workflows/pr.yaml, hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/StreamingManager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/85)
=> printout listener error

.github/workflows/pr.yaml, hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/wrapper/statelessAlgoWrapper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/87)
=> 2.4 log errors

hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/util/logger.py, hkube_python_wrapper/wrapper/algorunner.py, hkube_python_wrapper/wrapper/statelessAlgoWrapper.py
Log exception trace in one line
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/88)
=> Invoke stateless init with input values

.github/workflows/main.yaml, .github/workflows/trivy_fs.yaml
scan vulnerability as sarif and scan licenses as txt due to lack of feature support
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/91)
=> trivy license to txt format

hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/StreamingListener.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/wrapper/algorunner.py, tests/configs/config.py, tests/test_streaming.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/97)
=> bolk fetching

hkube_python_wrapper/wrapper/algorunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/100)
=> move stop algorithm method invocation to the end of stop streaming

hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, tests/test_streaming.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/106)
=> skip commit

hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/config/config.py, hkube_python_wrapper/wrapper/algorunner.py, tests/test_streaming.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/107)
=> Make delay configurable

hkube_python_wrapper/config/config.py, hkube_python_wrapper/wrapper/algorunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/108)
=> change configuration name

hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/112)
=> lock optimization

hkube_python_wrapper/codeApi/hkube_api.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/streaming/producerProcess.py, hkube_python_wrapper/wrapper/algorunner.py, setup.cfg, setup.py, tests/test_streaming.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/117)
=> Producer process

hkube_python_wrapper/communication/streaming/MessageListener.py, hkube_python_wrapper/communication/streaming/StreamingManager.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, hkube_python_wrapper/wrapper/algorunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/118)
=> isactive message listener variable

hkube_python_wrapper/wrapper/wc.py
Message will be logged every 1 minute instead of every 5 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/130)
=> isAlive message - logged every 1 minute

.github/workflows/pr.yaml, hkube_python_wrapper/communication/DataRequest.py, hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/python-wrapper.hkube/139)
=> remove 3.7
